#include "vk_util.h"

namespace bdex {

const char* vkResultName(VkResult r) {
    switch (r) {
#define C(x) case x: return #x;
        C(VK_SUCCESS) C(VK_NOT_READY) C(VK_TIMEOUT) C(VK_EVENT_SET) C(VK_EVENT_RESET) C(VK_INCOMPLETE)
        C(VK_SUBOPTIMAL_KHR) C(VK_ERROR_OUT_OF_DATE_KHR) C(VK_ERROR_SURFACE_LOST_KHR)
        C(VK_ERROR_OUT_OF_HOST_MEMORY) C(VK_ERROR_OUT_OF_DEVICE_MEMORY) C(VK_ERROR_INITIALIZATION_FAILED)
        C(VK_ERROR_DEVICE_LOST) C(VK_ERROR_MEMORY_MAP_FAILED) C(VK_ERROR_LAYER_NOT_PRESENT)
        C(VK_ERROR_EXTENSION_NOT_PRESENT) C(VK_ERROR_FEATURE_NOT_PRESENT) C(VK_ERROR_INCOMPATIBLE_DRIVER)
        C(VK_ERROR_TOO_MANY_OBJECTS) C(VK_ERROR_FORMAT_NOT_SUPPORTED) C(VK_ERROR_FRAGMENTED_POOL)
        C(VK_ERROR_OUT_OF_POOL_MEMORY) C(VK_ERROR_INVALID_EXTERNAL_HANDLE) C(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR)
        C(VK_ERROR_VALIDATION_FAILED_EXT) C(VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT)
#undef C
    default: return "VK_RESULT_UNKNOWN";
    }
}

} // namespace bdex
